/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 2
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_SEMI = 2,
  anon_sym_AT_COLON = 3,
  anon_sym_type_COLON = 4,
  anon_sym_DOLLAR_COLON = 5,
  anon_sym_BANG_COLON = 6,
  anon_sym_TODO_COLON = 7,
  aux_sym_todo_definition_token1 = 8,
  anon_sym_LPAREN = 9,
  anon_sym_DASH_DASH = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  sym_string = 16,
  sym_line_comment = 17,
  sym_block_comment = 18,
  sym_number = 19,
  sym_identifier = 20,
  sym_program = 21,
  sym_definition = 22,
  sym_word_definition = 23,
  sym_syntax_definition = 24,
  sym_type_definition = 25,
  sym_symbol_definition = 26,
  sym_constant_definition = 27,
  sym_todo_definition = 28,
  sym_stack_effect = 29,
  sym_expression = 30,
  sym_quotation = 31,
  sym_array = 32,
  sym_comment = 33,
  aux_sym_program_repeat1 = 34,
  aux_sym_word_definition_repeat1 = 35,
  aux_sym_stack_effect_repeat1 = 36,
  aux_sym_quotation_repeat1 = 37,
  anon_alias_sym_inputs = 38,
  anon_alias_sym_outputs = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_AT_COLON] = "@:",
  [anon_sym_type_COLON] = "type:",
  [anon_sym_DOLLAR_COLON] = "$:",
  [anon_sym_BANG_COLON] = "!:",
  [anon_sym_TODO_COLON] = "TODO:",
  [aux_sym_todo_definition_token1] = "todo_definition_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [sym_program] = "program",
  [sym_definition] = "definition",
  [sym_word_definition] = "word_definition",
  [sym_syntax_definition] = "syntax_definition",
  [sym_type_definition] = "type_definition",
  [sym_symbol_definition] = "symbol_definition",
  [sym_constant_definition] = "constant_definition",
  [sym_todo_definition] = "todo_definition",
  [sym_stack_effect] = "stack_effect",
  [sym_expression] = "expression",
  [sym_quotation] = "quotation",
  [sym_array] = "array",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_word_definition_repeat1] = "word_definition_repeat1",
  [aux_sym_stack_effect_repeat1] = "stack_effect_repeat1",
  [aux_sym_quotation_repeat1] = "quotation_repeat1",
  [anon_alias_sym_inputs] = "inputs",
  [anon_alias_sym_outputs] = "outputs",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_AT_COLON] = anon_sym_AT_COLON,
  [anon_sym_type_COLON] = anon_sym_type_COLON,
  [anon_sym_DOLLAR_COLON] = anon_sym_DOLLAR_COLON,
  [anon_sym_BANG_COLON] = anon_sym_BANG_COLON,
  [anon_sym_TODO_COLON] = anon_sym_TODO_COLON,
  [aux_sym_todo_definition_token1] = aux_sym_todo_definition_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [sym_program] = sym_program,
  [sym_definition] = sym_definition,
  [sym_word_definition] = sym_word_definition,
  [sym_syntax_definition] = sym_syntax_definition,
  [sym_type_definition] = sym_type_definition,
  [sym_symbol_definition] = sym_symbol_definition,
  [sym_constant_definition] = sym_constant_definition,
  [sym_todo_definition] = sym_todo_definition,
  [sym_stack_effect] = sym_stack_effect,
  [sym_expression] = sym_expression,
  [sym_quotation] = sym_quotation,
  [sym_array] = sym_array,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_word_definition_repeat1] = aux_sym_word_definition_repeat1,
  [aux_sym_stack_effect_repeat1] = aux_sym_stack_effect_repeat1,
  [aux_sym_quotation_repeat1] = aux_sym_quotation_repeat1,
  [anon_alias_sym_inputs] = anon_alias_sym_inputs,
  [anon_alias_sym_outputs] = anon_alias_sym_outputs,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TODO_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_todo_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_word_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_quotation] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stack_effect_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quotation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_inputs] = {
    .visible = true,
    .named = false,
  },
  [anon_alias_sym_outputs] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = anon_alias_sym_outputs,
  },
  [2] = {
    [1] = anon_alias_sym_inputs,
  },
  [3] = {
    [1] = anon_alias_sym_inputs,
    [3] = anon_alias_sym_outputs,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_stack_effect_repeat1, 3,
    aux_sym_stack_effect_repeat1,
    anon_alias_sym_inputs,
    anon_alias_sym_outputs,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 28,
  [32] = 27,
  [33] = 33,
  [34] = 30,
  [35] = 27,
  [36] = 28,
  [37] = 33,
  [38] = 29,
  [39] = 29,
  [40] = 33,
  [41] = 28,
  [42] = 27,
  [43] = 29,
  [44] = 33,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 5,
  [51] = 9,
  [52] = 16,
  [53] = 6,
  [54] = 17,
  [55] = 7,
  [56] = 7,
  [57] = 17,
  [58] = 16,
  [59] = 16,
  [60] = 17,
  [61] = 9,
  [62] = 7,
  [63] = 6,
  [64] = 9,
  [65] = 6,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '!', 14,
        '$', 15,
        '(', 48,
        ')', 51,
        '-', 8,
        '/', 5,
        '0', 66,
        ':', 32,
        ';', 34,
        '@', 16,
        'T', 20,
        '[', 53,
        ']', 55,
        's', 2,
        't', 24,
        '{', 57,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(61);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(79);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '{') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 11:
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '{') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 12:
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '}') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '{') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(44);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'O') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'O') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(71);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '!', 83,
        '$', 84,
        '/', 79,
        '0', 68,
        ':', 33,
        '@', 85,
        'T', 89,
        '[', 54,
        's', 77,
        't', 93,
        '{', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AT_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_type_COLON);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_type_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR_COLON);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAR_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BANG_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BANG_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_TODO_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_TODO_COLON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_todo_definition_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_todo_definition_token1);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '*') ADVANCE(80);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(81);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead == 'b') ADVANCE(25);
      if (lookahead == 'x') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '_') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(96);
      if (lookahead == '_') ADVANCE(95);
      if (lookahead == 'b') ADVANCE(94);
      if (lookahead == 'x') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(96);
      if (lookahead == '_') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(94);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(98);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(78);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(81);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(80);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(80);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(87);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(98);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 10},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 11},
  [65] = {.lex_state = 11},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 26},
  [78] = {.lex_state = 26},
  [79] = {.lex_state = 26},
  [80] = {.lex_state = 46},
  [81] = {.lex_state = 26},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_AT_COLON] = ACTIONS(1),
    [anon_sym_type_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR_COLON] = ACTIONS(1),
    [anon_sym_BANG_COLON] = ACTIONS(1),
    [anon_sym_TODO_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(82),
    [sym_definition] = STATE(3),
    [sym_word_definition] = STATE(4),
    [sym_syntax_definition] = STATE(4),
    [sym_type_definition] = STATE(4),
    [sym_symbol_definition] = STATE(4),
    [sym_constant_definition] = STATE(4),
    [sym_todo_definition] = STATE(4),
    [sym_expression] = STATE(3),
    [sym_quotation] = STATE(9),
    [sym_array] = STATE(9),
    [sym_comment] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_AT_COLON] = ACTIONS(7),
    [anon_sym_type_COLON] = ACTIONS(9),
    [anon_sym_DOLLAR_COLON] = ACTIONS(11),
    [anon_sym_BANG_COLON] = ACTIONS(13),
    [anon_sym_TODO_COLON] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(23),
    [sym_number] = ACTIONS(21),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym_definition] = STATE(2),
    [sym_word_definition] = STATE(4),
    [sym_syntax_definition] = STATE(4),
    [sym_type_definition] = STATE(4),
    [sym_symbol_definition] = STATE(4),
    [sym_constant_definition] = STATE(4),
    [sym_todo_definition] = STATE(4),
    [sym_expression] = STATE(2),
    [sym_quotation] = STATE(9),
    [sym_array] = STATE(9),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_AT_COLON] = ACTIONS(30),
    [anon_sym_type_COLON] = ACTIONS(33),
    [anon_sym_DOLLAR_COLON] = ACTIONS(36),
    [anon_sym_BANG_COLON] = ACTIONS(39),
    [anon_sym_TODO_COLON] = ACTIONS(42),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(48),
    [sym_string] = ACTIONS(51),
    [sym_line_comment] = ACTIONS(54),
    [sym_block_comment] = ACTIONS(54),
    [sym_number] = ACTIONS(51),
    [sym_identifier] = ACTIONS(51),
  },
  [STATE(3)] = {
    [sym_definition] = STATE(2),
    [sym_word_definition] = STATE(4),
    [sym_syntax_definition] = STATE(4),
    [sym_type_definition] = STATE(4),
    [sym_symbol_definition] = STATE(4),
    [sym_constant_definition] = STATE(4),
    [sym_todo_definition] = STATE(4),
    [sym_expression] = STATE(2),
    [sym_quotation] = STATE(9),
    [sym_array] = STATE(9),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_AT_COLON] = ACTIONS(7),
    [anon_sym_type_COLON] = ACTIONS(9),
    [anon_sym_DOLLAR_COLON] = ACTIONS(11),
    [anon_sym_BANG_COLON] = ACTIONS(13),
    [anon_sym_TODO_COLON] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(23),
    [sym_number] = ACTIONS(21),
    [sym_identifier] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(61), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [19] = 2,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [38] = 2,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [57] = 2,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [76] = 2,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(77), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [95] = 2,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [114] = 2,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(85), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [133] = 2,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [152] = 2,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(93), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [171] = 2,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(97), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [190] = 2,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(101), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [209] = 2,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(105), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [228] = 2,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(109), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [247] = 2,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [266] = 2,
    ACTIONS(115), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(117), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [285] = 2,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 11,
      anon_sym_COLON,
      anon_sym_AT_COLON,
      anon_sym_type_COLON,
      anon_sym_DOLLAR_COLON,
      anon_sym_BANG_COLON,
      anon_sym_TODO_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [304] = 7,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(26), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [332] = 7,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(23), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [360] = 7,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 1,
      anon_sym_SEMI,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(25), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [388] = 7,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(24), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [416] = 7,
    ACTIONS(139), 1,
      anon_sym_SEMI,
    ACTIONS(141), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
    ACTIONS(150), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(147), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(24), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [444] = 7,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(24), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [472] = 7,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(155), 1,
      anon_sym_SEMI,
    ACTIONS(131), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_quotation,
      sym_array,
    ACTIONS(129), 3,
      sym_string,
      sym_number,
      sym_identifier,
    STATE(24), 3,
      sym_expression,
      sym_comment,
      aux_sym_word_definition_repeat1,
  [500] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(41), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [523] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [546] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [569] = 6,
    ACTIONS(175), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 1,
      anon_sym_RBRACK,
    ACTIONS(180), 1,
      anon_sym_LBRACE,
    STATE(30), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(183), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [592] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [615] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [638] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
    STATE(30), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [661] = 6,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_LBRACK,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
    STATE(34), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(198), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [684] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [707] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [730] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(30), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [753] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(207), 1,
      anon_sym_RBRACK,
    STATE(37), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [776] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    STATE(40), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [799] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    STATE(30), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [822] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [845] = 6,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(36), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(61), 2,
      sym_quotation,
      sym_array,
    ACTIONS(163), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [868] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    STATE(44), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [891] = 6,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(30), 2,
      sym_expression,
      aux_sym_quotation_repeat1,
    STATE(64), 2,
      sym_quotation,
      sym_array,
    ACTIONS(173), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [914] = 5,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_expression,
    STATE(9), 2,
      sym_quotation,
      sym_array,
    ACTIONS(21), 3,
      sym_string,
      sym_number,
      sym_identifier,
  [933] = 2,
    ACTIONS(223), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(221), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [946] = 2,
    ACTIONS(227), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(225), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [959] = 2,
    ACTIONS(231), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(229), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [972] = 2,
    ACTIONS(235), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(233), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [985] = 2,
    ACTIONS(63), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [998] = 2,
    ACTIONS(79), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1011] = 2,
    ACTIONS(107), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(109), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1024] = 2,
    ACTIONS(67), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1037] = 2,
    ACTIONS(111), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1050] = 2,
    ACTIONS(71), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1063] = 1,
    ACTIONS(73), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1072] = 1,
    ACTIONS(113), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1081] = 1,
    ACTIONS(109), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1090] = 1,
    ACTIONS(109), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1099] = 1,
    ACTIONS(113), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1108] = 1,
    ACTIONS(81), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1117] = 1,
    ACTIONS(73), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1126] = 1,
    ACTIONS(69), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1135] = 1,
    ACTIONS(81), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1144] = 1,
    ACTIONS(69), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_string,
      sym_number,
      sym_identifier,
  [1153] = 3,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(66), 1,
      aux_sym_stack_effect_repeat1,
  [1163] = 3,
    ACTIONS(237), 1,
      anon_sym_DASH_DASH,
    ACTIONS(242), 1,
      sym_identifier,
    STATE(67), 1,
      aux_sym_stack_effect_repeat1,
  [1173] = 3,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      sym_identifier,
    STATE(73), 1,
      aux_sym_stack_effect_repeat1,
  [1183] = 3,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_stack_effect_repeat1,
  [1193] = 3,
    ACTIONS(251), 1,
      anon_sym_DASH_DASH,
    ACTIONS(253), 1,
      sym_identifier,
    STATE(67), 1,
      aux_sym_stack_effect_repeat1,
  [1203] = 3,
    ACTIONS(253), 1,
      sym_identifier,
    ACTIONS(255), 1,
      anon_sym_DASH_DASH,
    STATE(70), 1,
      aux_sym_stack_effect_repeat1,
  [1213] = 3,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_stack_effect_repeat1,
  [1223] = 3,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_stack_effect_repeat1,
  [1233] = 1,
    ACTIONS(261), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1238] = 1,
    ACTIONS(261), 2,
      anon_sym_DASH_DASH,
      sym_identifier,
  [1243] = 2,
    ACTIONS(263), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_stack_effect,
  [1250] = 1,
    ACTIONS(265), 1,
      sym_identifier,
  [1254] = 1,
    ACTIONS(267), 1,
      sym_identifier,
  [1258] = 1,
    ACTIONS(269), 1,
      sym_identifier,
  [1262] = 1,
    ACTIONS(271), 1,
      aux_sym_todo_definition_token1,
  [1266] = 1,
    ACTIONS(273), 1,
      sym_identifier,
  [1270] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1274] = 1,
    ACTIONS(277), 1,
      anon_sym_SEMI,
  [1278] = 1,
    ACTIONS(279), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 19,
  [SMALL_STATE(6)] = 38,
  [SMALL_STATE(7)] = 57,
  [SMALL_STATE(8)] = 76,
  [SMALL_STATE(9)] = 95,
  [SMALL_STATE(10)] = 114,
  [SMALL_STATE(11)] = 133,
  [SMALL_STATE(12)] = 152,
  [SMALL_STATE(13)] = 171,
  [SMALL_STATE(14)] = 190,
  [SMALL_STATE(15)] = 209,
  [SMALL_STATE(16)] = 228,
  [SMALL_STATE(17)] = 247,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 285,
  [SMALL_STATE(20)] = 304,
  [SMALL_STATE(21)] = 332,
  [SMALL_STATE(22)] = 360,
  [SMALL_STATE(23)] = 388,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 444,
  [SMALL_STATE(26)] = 472,
  [SMALL_STATE(27)] = 500,
  [SMALL_STATE(28)] = 523,
  [SMALL_STATE(29)] = 546,
  [SMALL_STATE(30)] = 569,
  [SMALL_STATE(31)] = 592,
  [SMALL_STATE(32)] = 615,
  [SMALL_STATE(33)] = 638,
  [SMALL_STATE(34)] = 661,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 707,
  [SMALL_STATE(37)] = 730,
  [SMALL_STATE(38)] = 753,
  [SMALL_STATE(39)] = 776,
  [SMALL_STATE(40)] = 799,
  [SMALL_STATE(41)] = 822,
  [SMALL_STATE(42)] = 845,
  [SMALL_STATE(43)] = 868,
  [SMALL_STATE(44)] = 891,
  [SMALL_STATE(45)] = 914,
  [SMALL_STATE(46)] = 933,
  [SMALL_STATE(47)] = 946,
  [SMALL_STATE(48)] = 959,
  [SMALL_STATE(49)] = 972,
  [SMALL_STATE(50)] = 985,
  [SMALL_STATE(51)] = 998,
  [SMALL_STATE(52)] = 1011,
  [SMALL_STATE(53)] = 1024,
  [SMALL_STATE(54)] = 1037,
  [SMALL_STATE(55)] = 1050,
  [SMALL_STATE(56)] = 1063,
  [SMALL_STATE(57)] = 1072,
  [SMALL_STATE(58)] = 1081,
  [SMALL_STATE(59)] = 1090,
  [SMALL_STATE(60)] = 1099,
  [SMALL_STATE(61)] = 1108,
  [SMALL_STATE(62)] = 1117,
  [SMALL_STATE(63)] = 1126,
  [SMALL_STATE(64)] = 1135,
  [SMALL_STATE(65)] = 1144,
  [SMALL_STATE(66)] = 1153,
  [SMALL_STATE(67)] = 1163,
  [SMALL_STATE(68)] = 1173,
  [SMALL_STATE(69)] = 1183,
  [SMALL_STATE(70)] = 1193,
  [SMALL_STATE(71)] = 1203,
  [SMALL_STATE(72)] = 1213,
  [SMALL_STATE(73)] = 1223,
  [SMALL_STATE(74)] = 1233,
  [SMALL_STATE(75)] = 1238,
  [SMALL_STATE(76)] = 1243,
  [SMALL_STATE(77)] = 1250,
  [SMALL_STATE(78)] = 1254,
  [SMALL_STATE(79)] = 1258,
  [SMALL_STATE(80)] = 1262,
  [SMALL_STATE(81)] = 1266,
  [SMALL_STATE(82)] = 1270,
  [SMALL_STATE(83)] = 1274,
  [SMALL_STATE(84)] = 1278,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quotation, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quotation, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_definition, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_definition, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_definition, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_syntax_definition, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_definition, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_definition, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_definition, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_syntax_definition, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_definition, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_definition, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_definition, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_todo_definition, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quotation, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quotation, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_definition, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_definition, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quotation_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stack_effect, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_effect, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stack_effect, 4, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_effect, 4, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stack_effect, 5, 0, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_effect, 5, 0, 3),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stack_effect, 4, 0, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_effect, 4, 0, 1),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stack_effect_repeat1, 2, 0, 0),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stack_effect_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stack_effect_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stack_effect_repeat1, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kette(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kette",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
